package view;

import Dao.ContratoDAO;
import Dao.AutenticacionDAO;
import Dao.RepresentanteAgenciaDAO;
import Dao.SeguroDAO;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.GuiUtils;

/**
 *
 * @author cristianorellanafarias
 */
public class AgregarContratosView extends javax.swing.JFrame {

    private AutenticacionDAO autenticacionDAO = new AutenticacionDAO();
    private ContratoDAO contratoDAO = new ContratoDAO();
    private RepresentanteAgenciaDAO representanteAgenciaDAO = new RepresentanteAgenciaDAO();
    private SeguroDAO seguroDAO = new SeguroDAO();

    private int montoPaquete = 0;
    private int montoSeguro = 0;
    
    
    /**
     * Creates new form AgregarContratos
     */
    public AgregarContratosView() {
        this.setMinimumSize(new Dimension(500, 620));
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo1.png")).getImage());
        this.ComboPaquete.setModel(GuiUtils.createModelFromList(contratoDAO.obtenerPaquete()));
        this.ComboColegio.setModel(GuiUtils.createModelFromList(contratoDAO.obtenerColegio()));
        this.comboagente.setModel(representanteAgenciaDAO.obtenerRepresentantes());
        this.cmbSeguro.setModel(seguroDAO.obtenerSeguro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblagente = new javax.swing.JLabel();
        comboagente = new javax.swing.JComboBox<>();
        lblcolegio = new javax.swing.JLabel();
        ComboColegio = new javax.swing.JComboBox<>();
        ComboCurso = new javax.swing.JComboBox<>();
        lblcurso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateChooserFechaEvento = new com.toedter.calendar.JDateChooser();
        ComboPaquete = new javax.swing.JComboBox<>();
        LblPaquete = new javax.swing.JLabel();
        lblmonto = new javax.swing.JLabel();
        cmbSeguro = new javax.swing.JComboBox<>();
        lblMontoValue = new javax.swing.JLabel();
        lblSeguro = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        BtnBorrarcampos = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("On Tour");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registrar Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        lblagente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblagente.setText("Agente Registrador:");
        jPanel1.add(lblagente);
        lblagente.setBounds(30, 60, 140, 20);

        comboagente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboagente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboagenteItemStateChanged(evt);
            }
        });
        jPanel1.add(comboagente);
        comboagente.setBounds(180, 50, 200, 40);

        lblcolegio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcolegio.setText("Seleccione Colegio:");
        jPanel1.add(lblcolegio);
        lblcolegio.setBounds(30, 110, 131, 20);

        ComboColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboColegio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboColegioItemStateChanged(evt);
            }
        });
        ComboColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboColegioActionPerformed(evt);
            }
        });
        jPanel1.add(ComboColegio);
        ComboColegio.setBounds(180, 100, 200, 40);

        ComboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Curso Asociado" }));
        ComboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCursoItemStateChanged(evt);
            }
        });
        jPanel1.add(ComboCurso);
        ComboCurso.setBounds(180, 150, 200, 40);

        lblcurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcurso.setText("Seleccione Curso:");
        jPanel1.add(lblcurso);
        lblcurso.setBounds(40, 150, 122, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha Evento : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 200, 106, 20);
        jPanel1.add(dateChooserFechaEvento);
        dateChooserFechaEvento.setBounds(180, 200, 200, 30);

        ComboPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboPaqueteItemStateChanged(evt);
            }
        });
        ComboPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPaqueteActionPerformed(evt);
            }
        });
        jPanel1.add(ComboPaquete);
        ComboPaquete.setBounds(180, 240, 200, 40);

        LblPaquete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblPaquete.setText("Paquete Turistico:");
        jPanel1.add(LblPaquete);
        LblPaquete.setBounds(40, 240, 125, 20);

        lblmonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmonto.setText("Monto Meta a cumplir:");
        jPanel1.add(lblmonto);
        lblmonto.setBounds(10, 290, 154, 20);

        cmbSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSeguro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSeguroItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbSeguro);
        cmbSeguro.setBounds(180, 320, 200, 40);

        lblMontoValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(lblMontoValue);
        lblMontoValue.setBounds(180, 280, 190, 30);

        lblSeguro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSeguro.setText("Seleccione Seguro:");
        jPanel1.add(lblSeguro);
        lblSeguro.setBounds(30, 330, 130, 20);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(140, 380, 260, 50);

        BtnBorrarcampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnBorrarcampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        BtnBorrarcampos.setText("Limpiar");
        BtnBorrarcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarcamposActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBorrarcampos);
        BtnBorrarcampos.setBounds(140, 460, 120, 40);

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return.png"))); // NOI18N
        BtnCancelar.setText("Volver");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar);
        BtnCancelar.setBounds(270, 460, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 440, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboColegioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboColegioItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String curso;
            curso = String.valueOf(ComboColegio.getSelectedItem());
            this.ComboCurso.setModel(GuiUtils.createModelFromList(contratoDAO.obtenerCurso(curso)));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_ComboColegioItemStateChanged

    private void BtnBorrarcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarcamposActionPerformed
        ComboPaquete.setSelectedIndex(0);
        ComboColegio.setSelectedIndex(0);
        comboagente.setSelectedIndex(0);
        ComboCurso.setSelectedIndex(0);
        dateChooserFechaEvento.setDate(null);
        lblmonto.setText(" ");

// TODO add your handling code here:
    }//GEN-LAST:event_BtnBorrarcamposActionPerformed

    private void ComboPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboPaqueteItemStateChanged
        //Obtención del monto del paquete
        String combopaq = String.valueOf(ComboPaquete.getSelectedItem());
        System.out.println("combopaq:"+ combopaq);
        this.montoPaquete = contratoDAO.obtenerMontoPaquete(combopaq);
        System.out.println("montoPaquete:"+ this.montoPaquete);
        int monto = this.calcularMontoResultado();
        if (monto > 0) {
            lblMontoValue.setText(String.valueOf(monto));
        }
    }//GEN-LAST:event_ComboPaqueteItemStateChanged

    private void ComboCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCursoItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCursoItemStateChanged

    private void comboagenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboagenteItemStateChanged

// TODO add your handling code here:
    }//GEN-LAST:event_comboagenteItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        try {
            //Obtención del monto del paquete
            String montopaq = String.valueOf(ComboPaquete.getSelectedItem());
            int montopaq1 = contratoDAO.obtenerMontoPaquete(montopaq);

            //Obtención rut agente
            String comboag = String.valueOf(comboagente.getSelectedItem());
            String comboag1 = representanteAgenciaDAO.obtenerRutRepresentante(comboag);

            int rutagente = Integer.parseInt(comboag1);
            System.out.println("Rut Agente: " + rutagente);
            
            String fecha_contrato = formato.format(new Date());
            System.out.println("Fecha de contrato: " + fecha_contrato);

            //Obtención ID CURSO (Para uso en el insert)//
            String combocur = String.valueOf(ComboCurso.getSelectedItem());
            String combocur1 = contratoDAO.obtenerIdCurso(combocur);
            int idcurso = Integer.parseInt(combocur1);

            System.out.println("id Curso : " + idcurso);

            String cmbseg = String.valueOf(cmbSeguro.getSelectedItem());
            String cmbseg1 = seguroDAO.obtenerIdSeguro(cmbseg);
            int idseguro = Integer.parseInt(cmbseg1);
            System.out.println("id seguro : " + idseguro);

            //Obtención Id Paquete (Para uso en el insert)//
            int idpaquete = Integer.parseInt(contratoDAO.obtenerIdPaquete(montopaq));
            System.out.println("ID Paquete: " + idpaquete);

            //Obtener Fecha Evento
            String fecha_evento = formato.format(dateChooserFechaEvento.getDate());
            System.out.println("Fecha_evento : " + fecha_evento);
            
            int monto = this.calcularMontoResultado();

            if (monto > 0) {
            
                contratoDAO.agregarContrato(idpaquete, rutagente, idcurso, idseguro, fecha_contrato, monto, fecha_evento);
                JOptionPane.showMessageDialog(this, "Contrato registrado");
            } else {
                JOptionPane.showMessageDialog(this, "Falta monto calculado");
            }
            

        } catch (Exception e) {
            e.printStackTrace();
//            lblmensaje.setText(e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuContratosView ConsultContr = new MenuContratosView();
        ConsultContr.setLocationRelativeTo(null);
        ConsultContr.setVisible(true);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void ComboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPaqueteActionPerformed

    private void ComboColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboColegioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboColegioActionPerformed

    private void cmbSeguroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSeguroItemStateChanged
        String comboseg = String.valueOf(cmbSeguro.getSelectedItem());
        System.out.println("comboseg:"+ comboseg);
        this.montoSeguro = seguroDAO.obtenerMontoSeguro(comboseg);
        System.out.println("montoSeguro:"+ this.montoSeguro);
        int monto = this.calcularMontoResultado();
        if (monto > 0) {
            lblMontoValue.setText(String.valueOf(monto));
        }
    }//GEN-LAST:event_cmbSeguroItemStateChanged

    
    private int calcularMontoResultado() {
        int monto = 0;
        if (this.montoPaquete > 0 && this.montoSeguro > 0) {
            int cantidadAlumnos = 1;
            monto = (this.montoPaquete * cantidadAlumnos) + (this.montoSeguro * cantidadAlumnos);
        }
        return monto;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarContratosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrarcampos;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JComboBox<String> ComboColegio;
    private javax.swing.JComboBox<String> ComboCurso;
    private javax.swing.JComboBox<String> ComboPaquete;
    private javax.swing.JLabel LblPaquete;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbSeguro;
    private javax.swing.JComboBox<String> comboagente;
    private com.toedter.calendar.JDateChooser dateChooserFechaEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMontoValue;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblagente;
    private javax.swing.JLabel lblcolegio;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblmonto;
    // End of variables declaration//GEN-END:variables
}
