package view;

import Dao.ContratoDAO;
import Dao.CursoDAO;
import controller.CursosController;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import model.Curso;
import utils.GuiUtils;

/**
 *
 * @author jose_
 */
public class AgregarCursosView extends javax.swing.JFrame {
    
    private CursosController controller = new CursosController();
    private ContratoDAO contratoDao = new ContratoDAO();
    private CursoDAO cursoDAO = new CursoDAO();

    /**
     * Creates new form AgregarContratos
     */
    public AgregarCursosView() {
        this.setUndecorated(true);
        this.setMinimumSize(new Dimension(510, 501));
        initComponents();
        setIconImage(GuiUtils.getImage("logo1.png"));
        this.cmbColegio.setModel(GuiUtils.createModelFromList(contratoDao.obtenerColegios()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblLogoMenu = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpanelRegistrarSeguro = new javax.swing.JPanel();
        lblColegio = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtNombreCurso = new javax.swing.JTextField();
        btnLimpiarApoderado = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblRutApoderadoEncargado = new javax.swing.JLabel();
        txtRutApoderado = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblNombreCurso1 = new javax.swing.JLabel();
        cmbColegio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("On Tour");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel3.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 30));

        lblLogoMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogoMenu.setText("On Tour");
        jPanel3.add(lblLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Exit.png"))); // NOI18N
        BtnCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseMoved(evt);
            }
        });
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseExited(evt);
            }
        });
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRegistrarSeguro.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRegistrarSeguro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 161, 215), 5, true), "Registrar Curso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jpanelRegistrarSeguro.setLayout(null);

        lblColegio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblColegio.setText("Colegio: ");
        jpanelRegistrarSeguro.add(lblColegio);
        lblColegio.setBounds(140, 90, 60, 20);

        lblMonto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpanelRegistrarSeguro.add(lblMonto);
        lblMonto.setBounds(180, 280, 190, 30);

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAgregarMouseMoved(evt);
            }
        });
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpanelRegistrarSeguro.add(btnAgregar);
        btnAgregar.setBounds(70, 250, 310, 60);

        txtNombreCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombreCurso.setBorder(null);
        jpanelRegistrarSeguro.add(txtNombreCurso);
        txtNombreCurso.setBounds(210, 120, 230, 40);

        btnLimpiarApoderado.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiarApoderado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        btnLimpiarApoderado.setText("Limpiar");
        btnLimpiarApoderado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimpiarApoderado.setIconTextGap(-1);
        btnLimpiarApoderado.setMargin(new java.awt.Insets(2, 4, 2, 14));
        btnLimpiarApoderado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLimpiarApoderadoMouseMoved(evt);
            }
        });
        btnLimpiarApoderado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarApoderadoMouseExited(evt);
            }
        });
        btnLimpiarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarApoderadoActionPerformed(evt);
            }
        });
        jpanelRegistrarSeguro.add(btnLimpiarApoderado);
        btnLimpiarApoderado.setBounds(70, 320, 150, 60);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(12, 161, 215));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return1.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolver.setIconTextGap(-10);
        btnVolver.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnVolver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVolverMouseMoved(evt);
            }
        });
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jpanelRegistrarSeguro.add(btnVolver);
        btnVolver.setBounds(240, 320, 140, 60);
        jpanelRegistrarSeguro.add(jSeparator1);
        jSeparator1.setBounds(30, 160, 410, 10);

        lblRutApoderadoEncargado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRutApoderadoEncargado.setText("Rut Apoderado encargado:");
        jpanelRegistrarSeguro.add(lblRutApoderadoEncargado);
        lblRutApoderadoEncargado.setBounds(30, 190, 190, 20);

        txtRutApoderado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRutApoderado.setBorder(null);
        jpanelRegistrarSeguro.add(txtRutApoderado);
        txtRutApoderado.setBounds(220, 170, 220, 40);
        jpanelRegistrarSeguro.add(jSeparator2);
        jSeparator2.setBounds(30, 210, 410, 10);

        lblNombreCurso1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreCurso1.setText("Nombre Curso:");
        jpanelRegistrarSeguro.add(lblNombreCurso1);
        lblNombreCurso1.setBounds(100, 140, 110, 20);

        cmbColegio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpanelRegistrarSeguro.add(cmbColegio);
        cmbColegio.setBounds(210, 80, 230, 40);

        jPanel1.add(jpanelRegistrarSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 510, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            String combocur = String.valueOf(cmbColegio.getSelectedItem());
            String combocur1 = contratoDao.obtenerIdColegio(combocur);
            int idcolegio = Integer.parseInt(combocur1);
            
            System.out.println("id Curso : " + idcolegio);
            
            String nombre = txtNombreCurso.getText();
            
            int rutApoderado = Integer.parseInt(txtRutApoderado.getText());
            System.out.println("apoderado: " + rutApoderado);
            
            if (nombre.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Nombre curso debe ser completado");
            } else {
                Curso curso = new Curso();
                curso.setNombre(nombre);
                curso.setIdColegio(idcolegio);
                curso.setRutEncargado(rutApoderado);
                
                boolean agregado = controller.agregarCurso(curso);
                
                if (agregado) {
                    JOptionPane.showMessageDialog(this, "Curso registrado");
                } else {
                    JOptionPane.showMessageDialog(this, "El Curso no se pudo registrar", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
//            lblmensaje.setText(e.getMessage());
            JOptionPane.showMessageDialog(this, "Falta completar campos vacíos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarApoderadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarApoderadoMouseMoved
        // TODO add your handling code here:
        btnLimpiarApoderado.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnLimpiarApoderadoMouseMoved

    private void btnLimpiarApoderadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarApoderadoMouseExited
        // TODO add your handling code here:
        btnLimpiarApoderado.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnLimpiarApoderadoMouseExited

    private void btnLimpiarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarApoderadoActionPerformed
        // TODO add your handling code here:
        cmbColegio.setSelectedIndex(0);
        txtNombreCurso.setText("");
        txtRutApoderado.setText("");
    }//GEN-LAST:event_btnLimpiarApoderadoActionPerformed

    private void btnVolverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseMoved
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnVolverMouseMoved

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuColegioView menuColegios = new MenuColegioView();
        menuColegios.setLocationRelativeTo(null);
        menuColegios.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseMoved
        // TODO add your handling code here:
        btnAgregar.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnAgregarMouseMoved

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        // TODO add your handling code here:
        btnAgregar.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(MenuPrincipalView.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void BtnCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseMoved
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_BtnCerrarMouseMoved

    private void BtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseExited
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_BtnCerrarMouseExited

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir de la aplicación?");
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCursosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiarApoderado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbColegio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpanelRegistrarSeguro;
    private javax.swing.JLabel lblColegio;
    private javax.swing.JLabel lblLogoMenu;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreCurso1;
    private javax.swing.JLabel lblRutApoderadoEncargado;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtRutApoderado;
    // End of variables declaration//GEN-END:variables
}
