/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.ContratoDAO;
import Dao.AutenticacionDAO;
import Dao.RepresentanteAgenciaDAO;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author cristianorellanafarias
 */
public class AgregarContratosView extends javax.swing.JFrame {

    private AutenticacionDAO autenticacionDAO = new AutenticacionDAO();
    private ContratoDAO contratoDAO = new ContratoDAO();
    private RepresentanteAgenciaDAO representanteAgenciaDAO = new RepresentanteAgenciaDAO();
    
    /**
     * Creates new form AgregarContratos
     */
    public AgregarContratosView() {
        this.setMinimumSize(new Dimension(468, 550));
        initComponents();
        this.ComboPaquete.setModel(contratoDAO.obtenerPaquete());
        this.ComboColegio.setModel(contratoDAO.obtenerColegio());
        this.comboagente.setModel(representanteAgenciaDAO.obtenerRepresentantes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPaquete = new javax.swing.JLabel();
        ComboPaquete = new javax.swing.JComboBox<>();
        lblagente = new javax.swing.JLabel();
        lblcolegio = new javax.swing.JLabel();
        ComboColegio = new javax.swing.JComboBox<>();
        ComboCurso = new javax.swing.JComboBox<>();
        lblcurso = new javax.swing.JLabel();
        lblmonto = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        BtnBorrarcampos = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        comboagente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtfechaevento = new javax.swing.JTextField();
        LblTituloAgregarContrato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LblPaquete.setText("Seleccionar Paquete Turistico:");
        getContentPane().add(LblPaquete);
        LblPaquete.setBounds(43, 141, 174, 16);

        ComboPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboPaqueteItemStateChanged(evt);
            }
        });
        ComboPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPaqueteActionPerformed(evt);
            }
        });
        getContentPane().add(ComboPaquete);
        ComboPaquete.setBounds(224, 138, 186, 22);

        lblagente.setText("Agente Registrador:");
        getContentPane().add(lblagente);
        lblagente.setBounds(43, 173, 115, 16);

        lblcolegio.setText("Seleccione Colegio:");
        getContentPane().add(lblcolegio);
        lblcolegio.setBounds(43, 202, 112, 16);

        ComboColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboColegio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboColegioItemStateChanged(evt);
            }
        });
        ComboColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboColegioActionPerformed(evt);
            }
        });
        getContentPane().add(ComboColegio);
        ComboColegio.setBounds(224, 202, 186, 22);

        ComboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Curso Asociado" }));
        ComboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCursoItemStateChanged(evt);
            }
        });
        getContentPane().add(ComboCurso);
        ComboCurso.setBounds(224, 231, 186, 22);

        lblcurso.setText("Seleccione Curso:");
        getContentPane().add(lblcurso);
        lblcurso.setBounds(43, 231, 122, 16);

        lblmonto.setText("Monto Meta a cumplir:");
        getContentPane().add(lblmonto);
        lblmonto.setBounds(43, 300, 129, 16);

        btnAgregar.setText("Agregar Contrato");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(50, 360, 131, 25);

        BtnBorrarcampos.setText("Borrar Campos");
        BtnBorrarcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarcamposActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBorrarcampos);
        BtnBorrarcampos.setBounds(200, 360, 119, 25);

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar);
        BtnCancelar.setBounds(330, 360, 83, 25);
        getContentPane().add(lblmensaje);
        lblmensaje.setBounds(200, 390, 170, 30);
        getContentPane().add(lblMonto);
        lblMonto.setBounds(230, 300, 151, 28);

        comboagente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboagente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboagenteItemStateChanged(evt);
            }
        });
        getContentPane().add(comboagente);
        comboagente.setBounds(224, 167, 186, 22);

        jLabel1.setText("Fecha Evento : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 271, 89, 16);
        getContentPane().add(txtfechaevento);
        txtfechaevento.setBounds(224, 271, 170, 22);

        LblTituloAgregarContrato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTituloAgregarContrato.setText("Agregar Contrato:");
        getContentPane().add(LblTituloAgregarContrato);
        LblTituloAgregarContrato.setBounds(52, 23, 163, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboColegioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboColegioItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String curso;
            curso = String.valueOf(ComboColegio.getSelectedItem());
            this.ComboCurso.setModel(contratoDAO.obtenerCurso(curso));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_ComboColegioItemStateChanged

    private void BtnBorrarcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarcamposActionPerformed
        ComboPaquete.setSelectedIndex(0);
        ComboColegio.setSelectedIndex(0);
        comboagente.setSelectedIndex(0);
        ComboCurso.setSelectedIndex(0);
        txtfechaevento.setText(" ");
        lblmonto.setText(" ");

        lblmensaje.setText("Campos Reseteados correctamente");

// TODO add your handling code here:
    }//GEN-LAST:event_BtnBorrarcamposActionPerformed

    private void ComboPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboPaqueteItemStateChanged
        //Obtención del monto del paquete
        String combopaq = String.valueOf(ComboPaquete.getSelectedItem());
        String combopaq1;

        combopaq1 = contratoDAO.obtenerMontoPaquete(combopaq);

        lblMonto.setText("$" + combopaq1);
        //=============================//

// TODO add your handling code here:
    }//GEN-LAST:event_ComboPaqueteItemStateChanged

    private void ComboCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCursoItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCursoItemStateChanged

    private void comboagenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboagenteItemStateChanged

// TODO add your handling code here:
    }//GEN-LAST:event_comboagenteItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try {
            //Obtención del monto del paquete
            String montopaq = String.valueOf(ComboPaquete.getSelectedItem());
            String montopaq1;

            montopaq1 = contratoDAO.obtenerMontoPaquete(montopaq);

            int monto = Integer.parseInt(montopaq1);

            System.out.println("monto: " + monto);

            //Obtención rut agente
            String comboag = String.valueOf(comboagente.getSelectedItem());
            String comboag1 = representanteAgenciaDAO.obtenerRutRepresentante(comboag);

            int rutagente = Integer.parseInt(comboag1);
            System.out.println("Rut Agente: " + rutagente);

            

           Calendar fcontrato = Calendar.getInstance();
           
          int dia = fcontrato.get(Calendar.DATE);
          int mes = fcontrato.get(Calendar.MONTH);
          int anio = fcontrato.get(Calendar.YEAR);
          
         String fecha_contrato= new String();
         fecha_contrato= String.valueOf(dia)+"/"+String.valueOf(mes+1)+"/"+String.valueOf(anio);
         
            System.out.println(fecha_contrato);
           

            //Obtención ID CURSO (Para uso en el insert)//
            String combocur = String.valueOf(ComboCurso.getSelectedItem());
            String combocur1 = contratoDAO.obtenerIdCurso(combocur);
            int idcurso = Integer.parseInt(combocur1);

            System.out.println("id Curso : " + idcurso);

            //Obtención Id Paquete (Para uso en el insert)//
            int idpaquete = Integer.parseInt(contratoDAO.obtenerIdPaquete(montopaq));
            System.out.println("ID PAquete: " + idpaquete);

            //Obtener Fecha Evento
            String fecha_evento = txtfechaevento.getText();

            System.out.println("Fecha_evento : " + fecha_evento);
            
            //Obtener Fecha Del sistema
            
            

            contratoDAO.agregarContrato(idpaquete, rutagente, idcurso, fecha_contrato, monto, fecha_evento);

            lblmensaje.setText("Contrato Agregado Correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            lblmensaje.setText(e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ConsultaContratosView ConsultContr = new ConsultaContratosView();
        ConsultContr.setLocationRelativeTo(null);
        ConsultContr.setVisible(true);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void ComboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPaqueteActionPerformed

    private void ComboColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboColegioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboColegioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarContratosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrarcampos;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JComboBox<String> ComboColegio;
    private javax.swing.JComboBox<String> ComboCurso;
    private javax.swing.JComboBox<String> ComboPaquete;
    private javax.swing.JLabel LblPaquete;
    private javax.swing.JLabel LblTituloAgregarContrato;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> comboagente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblagente;
    private javax.swing.JLabel lblcolegio;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lblmonto;
    private javax.swing.JTextField txtfechaevento;
    // End of variables declaration//GEN-END:variables
}
