package view;

import Dao.ContratoDAO;
import Dao.AutenticacionDAO;
import Dao.RepresentanteAgenciaDAO;
import Dao.SeguroDAO;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.KeyValue;
import utils.GuiUtils;

/**
 *
 * @author cristianorellanafarias
 */
public class AgregarContratosView extends javax.swing.JFrame {

    private AutenticacionDAO autenticacionDao = new AutenticacionDAO();
    private ContratoDAO contratoDao = new ContratoDAO();
    private RepresentanteAgenciaDAO representanteAgenciaDao = new RepresentanteAgenciaDAO();
    private SeguroDAO seguroDao = new SeguroDAO();

    private int montoPaquete = 0;
    private int montoSeguro = 0;
    private int cantidadAlumnos = 0;

    /**
     * Creates new form AgregarContratos
     */
    public AgregarContratosView() {
        this.setUndecorated(true);
        this.setMinimumSize(new Dimension(470, 620));
        initComponents();
        setIconImage(GuiUtils.getImage("logo1.png"));
        this.cmbPaquete.setModel(GuiUtils.createModelFromList(contratoDao.obtenerPaquetes()));
        this.cmbColegio.setModel(GuiUtils.createModelFromList(contratoDao.obtenerColegios()));
        this.cmbAgente.setModel(representanteAgenciaDao.obtenerRepresentantes());
        this.cmbSeguro.setModel(seguroDao.obtenerSeguro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblagente = new javax.swing.JLabel();
        cmbAgente = new javax.swing.JComboBox<>();
        lblcolegio = new javax.swing.JLabel();
        cmbColegio = new javax.swing.JComboBox<>();
        cmbCurso = new javax.swing.JComboBox<>();
        lblcurso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateChooserFechaEvento = new com.toedter.calendar.JDateChooser();
        cmbPaquete = new javax.swing.JComboBox<>();
        LblPaquete = new javax.swing.JLabel();
        cmbSeguro = new javax.swing.JComboBox<>();
        lblSeguro = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblMontoValue = new javax.swing.JLabel();
        lblmonto = new javax.swing.JLabel();
        btnLimpiarContrato = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblLogoMenu = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("On Tour");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 161, 215), 5, true), "Registrar Contrato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblagente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblagente.setText("Agente Registrador:");
        jPanel1.add(lblagente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        cmbAgente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAgenteItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, 40));

        lblcolegio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcolegio.setText("Seleccione Colegio:");
        jPanel1.add(lblcolegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        cmbColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColegio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbColegioItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 40));

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Curso Asociado" }));
        cmbCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCursoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, 40));

        lblcurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcurso.setText("Seleccione Curso:");
        jPanel1.add(lblcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 122, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha Evento : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 20));
        jPanel1.add(dateChooserFechaEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 200, 30));

        cmbPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaqueteItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 200, 40));

        LblPaquete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblPaquete.setText("Paquete Turistico:");
        jPanel1.add(LblPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        cmbSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSeguro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSeguroItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, 40));

        lblSeguro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSeguro.setText("Seleccione Seguro:");
        jPanel1.add(lblSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnAgregar.setText("Guardar Contrato");
        btnAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAgregarMouseMoved(evt);
            }
        });
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 360, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMontoValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMontoValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblMontoValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 20));

        lblmonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmonto.setText("TOTAL CONTRATO: $ ");
        jPanel4.add(lblmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 360, 50));

        btnLimpiarContrato.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiarContrato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        btnLimpiarContrato.setText("Limpiar");
        btnLimpiarContrato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimpiarContrato.setIconTextGap(-1);
        btnLimpiarContrato.setMargin(new java.awt.Insets(2, 4, 2, 14));
        btnLimpiarContrato.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLimpiarContratoMouseMoved(evt);
            }
        });
        btnLimpiarContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarContratoMouseExited(evt);
            }
        });
        btnLimpiarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarContratoActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 50));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 10, 50));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(12, 161, 215));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return1.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolver.setIconTextGap(-10);
        btnVolver.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnVolver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVolverMouseMoved(evt);
            }
        });
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 440, 550));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel3.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 30));

        lblLogoMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogoMenu.setText("On Tour");
        jPanel3.add(lblLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Exit.png"))); // NOI18N
        BtnCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseMoved(evt);
            }
        });
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseExited(evt);
            }
        });
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbColegioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbColegioItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String curso;
            curso = String.valueOf(cmbColegio.getSelectedItem());
            this.cmbCurso.setModel(GuiUtils.createModelFromList(contratoDao.obtenerCursos(curso)));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_cmbColegioItemStateChanged

    private void cmbPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaqueteItemStateChanged
        //Obtención del monto del paquete
        String combopaq = String.valueOf(cmbPaquete.getSelectedItem());
        System.out.println("combopaq:" + combopaq);
        this.montoPaquete = contratoDao.obtenerMontoPaquete(combopaq);
        System.out.println("montoPaquete:" + this.montoPaquete);
        int monto = this.calcularMontoResultado();
        if (monto > 0) {
            lblMontoValue.setText(String.valueOf(monto));
        }
    }//GEN-LAST:event_cmbPaqueteItemStateChanged

    private void cmbCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCursoItemStateChanged

        String combopaq = String.valueOf(cmbCurso.getSelectedItem());
        System.out.println("combo curso:" + combopaq);
        cantidadAlumnos = contratoDao.obtenerCatidadAlumnos(combopaq);
        System.out.println("cantidad alumnos: " + cantidadAlumnos);
        int monto = this.calcularMontoResultado();
        if (monto > 0) {
            lblMontoValue.setText(String.valueOf(monto));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoItemStateChanged

    private void cmbAgenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAgenteItemStateChanged

// TODO add your handling code here:
    }//GEN-LAST:event_cmbAgenteItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        try {
            //Obtención del monto del paquete
            String descripcion = String.valueOf(cmbPaquete.getSelectedItem());

            //Obtención rut agente
            KeyValue representante = (KeyValue) cmbAgente.getSelectedItem();
            int rutRepresentante = representante.getId();

            String fecha_contrato = formato.format(new Date());
            System.out.println("Fecha de contrato: " + fecha_contrato);

            //Obtención ID CURSO (Para uso en el insert)//
            String combocur = String.valueOf(cmbCurso.getSelectedItem());
            String combocur1 = contratoDao.obtenerIdCurso(combocur);
            int idcurso = Integer.parseInt(combocur1);

            System.out.println("id Curso : " + idcurso);

            String cmbseg = String.valueOf(cmbSeguro.getSelectedItem());
            String cmbseg1 = seguroDao.obtenerIdSeguro(cmbseg);
            int idseguro = Integer.parseInt(cmbseg1);
            System.out.println("id seguro : " + idseguro);

            //Obtención Id Paquete (Para uso en el insert)//
            int idpaquete = Integer.parseInt(contratoDao.obtenerIdPaquete(descripcion));
            System.out.println("ID Paquete: " + idpaquete);

            //Obtener Fecha Evento
            String fecha_evento = formato.format(dateChooserFechaEvento.getDate());
            System.out.println("Fecha_evento : " + fecha_evento);

            int monto = this.calcularMontoResultado();

            if (monto > 0) {
                contratoDao.agregarContrato(idpaquete, rutRepresentante, idcurso, idseguro, fecha_contrato, monto, fecha_evento);
                JOptionPane.showMessageDialog(this, "Contrato registrado");
            } else {
                JOptionPane.showMessageDialog(this, "Falta monto calculado");
            }

        } catch (Exception e) {
            e.printStackTrace();
//            lblmensaje.setText(e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbSeguroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSeguroItemStateChanged
        String comboseg = String.valueOf(cmbSeguro.getSelectedItem());
        System.out.println("comboseg:" + comboseg);
        this.montoSeguro = seguroDao.obtenerMontoSeguro(comboseg);
        System.out.println("montoSeguro:" + this.montoSeguro);
        int monto = this.calcularMontoResultado();
        if (monto > 0) {
            lblMontoValue.setText(String.valueOf(monto));
        }
    }//GEN-LAST:event_cmbSeguroItemStateChanged

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved

        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(MenuPrincipalView.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited

        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void BtnCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseMoved
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_BtnCerrarMouseMoved

    private void BtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseExited
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_BtnCerrarMouseExited

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir de la aplicación?");
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void btnLimpiarContratoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarContratoMouseMoved
        // TODO add your handling code here:
        btnLimpiarContrato.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnLimpiarContratoMouseMoved

    private void btnLimpiarContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarContratoMouseExited
        // TODO add your handling code here:
        btnLimpiarContrato.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnLimpiarContratoMouseExited

    private void btnVolverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseMoved
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnVolverMouseMoved

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuContratosView ConsultContr = new MenuContratosView();
        ConsultContr.setLocationRelativeTo(null);
        ConsultContr.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseMoved
        // TODO add your handling code here:
        btnAgregar.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnAgregarMouseMoved

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        // TODO add your handling code here:
        btnAgregar.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnLimpiarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarContratoActionPerformed
        // TODO add your handling code here:
        cmbAgente.setSelectedIndex(0);
        cmbColegio.setSelectedIndex(0);
        cmbCurso.setSelectedIndex(0);
        dateChooserFechaEvento.setDate(null);
        cmbPaquete.setSelectedIndex(0);
        cmbSeguro.setSelectedIndex(0);
        lblMontoValue.setText(" ");
    }//GEN-LAST:event_btnLimpiarContratoActionPerformed

    private int calcularMontoResultado() {
        int monto = 0;
        if (this.montoPaquete > 0 && this.montoSeguro > 0 && this.cantidadAlumnos > 0) {
            int cantidadAlumnos = this.cantidadAlumnos;
            monto = (this.montoPaquete * cantidadAlumnos) + (this.montoSeguro * cantidadAlumnos);
        }
        return monto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarContratosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarContratosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JLabel LblPaquete;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiarContrato;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbAgente;
    private javax.swing.JComboBox<String> cmbColegio;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbPaquete;
    private javax.swing.JComboBox<String> cmbSeguro;
    private com.toedter.calendar.JDateChooser dateChooserFechaEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblLogoMenu;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblMontoValue;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblagente;
    private javax.swing.JLabel lblcolegio;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblmonto;
    // End of variables declaration//GEN-END:variables
}
