/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.AlumnoDAO;
import Dao.ApoderadoDAO;
import Dao.CiudadDAO;
import Dao.ComunaDAO;
import Dao.Conexion;
import Dao.ContratoDAO;
import com.mxrck.autocompleter.TextAutoCompleter;
import controller.AlumnosController;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Alumno;
import utils.GuiUtils;

/**
 *
 * @author cristianorellanafarias
 */
public class AgregarAlumnosView extends javax.swing.JFrame {

    private ApoderadoDAO apoderadoDAO = new ApoderadoDAO();
    private ContratoDAO contratoDao = new ContratoDAO();
    private ComunaDAO comunaDao = new ComunaDAO();
    private CiudadDAO ciudadDao = new CiudadDAO();
    private AlumnoDAO alumnoDao = new AlumnoDAO();
    private AlumnosController alcontroller= new AlumnosController();

    /**
     * Creates new form AgregarAlumnosView
     */
    public AgregarAlumnosView() {
        this.setUndecorated(true);
        this.setMinimumSize(new Dimension(593, 783));
        initComponents();
        
        ArrayList<Object> lstNombres = apoderadoDAO.buscarNombresApoderados();
        
        TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtApoderado);
        textAutoCompleter.setItems(lstNombres);
        
        this.cmbColegio.setModel(GuiUtils.createModelFromList(contratoDao.obtenerColegios()));
        this.cmbCiudad.setModel(ciudadDao.obtenerCiudades());
        this.lblCurso.setVisible(false);
        this.cmbCurso.setVisible(false);
        this.lblComuna.setVisible(false);
        this.cmbComuna.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblLogoMenu = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtApoderado = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtRut_Alumno = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtApaterno = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmbColegio = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        cmbCiudad = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        cmbComuna = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        DateChooserFnacimiento = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogoMenu.setText("On Tour");
        jPanel3.add(lblLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel3.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 30));

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Exit.png"))); // NOI18N
        BtnCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseMoved(evt);
            }
        });
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseExited(evt);
            }
        });
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 30, 30));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 590, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 161, 215), 5, true), "Registrar Alumnos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre apoderado:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        txtApoderado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApoderado.setToolTipText("Ingrese el nombre del apoderado");
        txtApoderado.setBorder(null);
        txtApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoderadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 250, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 430, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rut:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 30, -1));

        txtRut_Alumno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRut_Alumno.setBorder(null);
        jPanel2.add(txtRut_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 194, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 390, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombres:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 194, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 240, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Apellido Paterno:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, -1));

        txtApaterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApaterno.setBorder(null);
        jPanel2.add(txtApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 194, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 240, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Apellido Materno:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        txtAMaterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAMaterno.setBorder(null);
        jPanel2.add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 194, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 240, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Colegio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 60, -1));

        cmbColegio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbColegio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbColegioItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 194, 30));

        lblCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCurso.setText("Curso:");
        jPanel2.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 50, -1));

        cmbCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(cmbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 194, 30));

        cmbCiudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCiudadItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 194, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ciudad:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, -1));

        lblComuna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblComuna.setText("Comuna:");
        jPanel2.add(lblComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 70, -1));

        cmbComuna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(cmbComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 194, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Dirección:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 70, -1));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDireccion.setBorder(null);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 194, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 240, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Fecha de Nacimiento:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, -1));

        DateChooserFnacimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(DateChooserFnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 170, 30));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefono.setBorder(null);
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 192, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Telefono:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 70, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 240, 10));

        btnRegistrarAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarAlumno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrarAlumno.setText("Registrar");
        btnRegistrarAlumno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegistrarAlumnoMouseMoved(evt);
            }
        });
        btnRegistrarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarAlumnoMouseExited(evt);
            }
        });
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 320, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 450, 600));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(12, 161, 215));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return1.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolver.setIconTextGap(-10);
        btnVolver.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnVolver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVolverMouseMoved(evt);
            }
        });
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 590, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoderadoActionPerformed

    private void cmbColegioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbColegioItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String curso;
            this.lblCurso.setVisible(true);
            this.cmbCurso.setVisible(true);
            curso = String.valueOf(cmbColegio.getSelectedItem());
            this.cmbCurso.setModel(GuiUtils.createModelFromList(contratoDao.obtenerCursos(curso)));
        }
    }//GEN-LAST:event_cmbColegioItemStateChanged

    private void cmbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCiudadItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String comuna;
            comuna = String.valueOf(cmbCiudad.getSelectedItem());
            this.cmbComuna.setVisible(true);
            this.lblComuna.setVisible(true);
            this.cmbComuna.setModel(comunaDao.obtenerComunas(comuna));
        }
    }//GEN-LAST:event_cmbCiudadItemStateChanged

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        try {
            String apoderado = txtApoderado.getText();

            int rut_apoderado = alumnoDao.obtenerRutApoderado(apoderado);
            
            int rut_alumno=Integer.parseInt(txtRut_Alumno.getText());
            String nombre=txtNombre.getText();
            String amaterno=txtAMaterno.getText();
            String apaterno=txtApaterno.getText();
            String direccion=txtDireccion.getText();
            int telefono=Integer.parseInt(txtTelefono.getText());
            
             //Obtención ID CURSO (Para uso en el insert)//
            String combocur = String.valueOf(cmbCurso.getSelectedItem());
            String combocur1 = contratoDao.obtenerIdCurso(combocur);
            int idcurso = Integer.parseInt(combocur1);
            
            
             //Obtención ID COMUNA (Para uso en el insert)//
            String comuna = String.valueOf(cmbComuna.getSelectedItem());
            int idcomuna= comunaDao.obtenerIDComuna(comuna);
                

            System.out.println("apoderado: " + apoderado);
            System.out.println("Rut apoderado: " + rut_apoderado);
            System.out.println("rut alumno"+rut_alumno);
            System.out.println("nombre completo:"+nombre+apaterno+amaterno);
            System.out.println("idcomuna "+idcomuna);
            System.out.println("idcurso"+ idcurso);
            

            String fecha_nacimiento = formato.format(DateChooserFnacimiento.getDate());
            System.out.println("Fecha Nacimiento : " + fecha_nacimiento);
            
            
            
            //Agregar a la BD
         Alumno alumno = new Alumno();
         alumno.setRut(rut_alumno);
         alumno.setIdcomuna(idcomuna);
         alumno.setIdcurso(idcurso);
         alumno.setMonto(0);
         alumno.setRut_apoderado(rut_apoderado);
         alumno.setNombre(nombre);
         alumno.setaPaterno(apaterno);
         alumno.setaMaterno(amaterno);
         alumno.setTelefono(telefono);
         alumno.setDireccion(direccion);
         alumno.setFechaNacimiento(fecha_nacimiento);
        
         
         alcontroller.agregarAlumno(alumno);
         
         JOptionPane.showMessageDialog(null,"Alumno Agregado correctamente");
         
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved

        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(MenuPrincipalView.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited

        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void BtnCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseMoved
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_BtnCerrarMouseMoved

    private void BtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseExited
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_BtnCerrarMouseExited

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir de la aplicación?");
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void btnRegistrarAlumnoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoMouseMoved
        // TODO add your handling code here:
        btnRegistrarAlumno.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnRegistrarAlumnoMouseMoved

    private void btnRegistrarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoMouseExited
        // TODO add your handling code here:
        btnRegistrarAlumno.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnRegistrarAlumnoMouseExited

    private void btnVolverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseMoved
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnVolverMouseMoved

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuAlumnosView menuAlumnos = new MenuAlumnosView();
        menuAlumnos.setLocationRelativeTo(null);
        menuAlumnos.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAlumnosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private com.toedter.calendar.JDateChooser DateChooserFnacimiento;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbColegio;
    private javax.swing.JComboBox<String> cmbComuna;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblLogoMenu;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JTextField txtApoderado;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut_Alumno;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
