/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ApoderadosController;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose_
 */
public final class MenuApoderadoView extends javax.swing.JFrame {

    private ApoderadosController controller = new ApoderadosController();

    DefaultTableModel modelo;

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuApoderadoView() {
        this.setMinimumSize(new Dimension(860, 500));
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo1.png")).getImage());
        this.BtnModificarApoderado.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupPerfil = new javax.swing.ButtonGroup();
        BtnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableApoderados = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnRegistrarApoderado = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnModificarApoderado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BtnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return.png"))); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver);
        BtnVolver.setBounds(630, 410, 150, 40);

        tableApoderados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableApoderados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 750, 230);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(0, 0, 186, 170);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Administrador Apoderados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        BtnRegistrarApoderado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnRegistrarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AddApoderado.png"))); // NOI18N
        BtnRegistrarApoderado.setText("Registrar");
        BtnRegistrarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarApoderadoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrarApoderado);
        BtnRegistrarApoderado.setBounds(10, 30, 170, 70);

        BtnListar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        BtnListar.setText("Listar");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnListar);
        BtnListar.setBounds(200, 30, 140, 70);

        BtnModificarApoderado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnModificarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EditApoderado.png"))); // NOI18N
        BtnModificarApoderado.setText("Modificar");
        BtnModificarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarApoderadoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificarApoderado);
        BtnModificarApoderado.setBounds(360, 30, 170, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 40, 610, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void actualizarApoderado(){
//        try {
//        List<Apoderado> apoderado;
//        modelo.setRowCount(0);
//        apoderado = ApoderadoDAO.listarApoderado();
//            for (Apoderado apoderadoa : apoderado) {
//                Object[] obj= ApoderadoDAO.objetoApoderado(apoderadoa);
//                modelo.addRow(obj);
//                this.TbListar.setModel(modelo);
//                
//            }
//        } catch (SQLException e) {
//        }
//    }

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        // TODO add your handling code here:
        this.jScrollPane1.setVisible(true);

        DefaultTableModel modelotabla = this.controller.consultarApoderados();
        this.tableApoderados.setModel(modelotabla);
        this.BtnModificarApoderado.setVisible(true);
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipalView MenuPrin = new MenuPrincipalView();
        MenuPrin.setLocationRelativeTo(null);
        MenuPrin.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnRegistrarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarApoderadoActionPerformed
        // TODO add your handling code here:
        AgregarApoderadosView AgregarApod = new AgregarApoderadosView();
        this.setVisible(false);
        AgregarApod.setLocationRelativeTo(null);
        AgregarApod.setVisible(true);

    }//GEN-LAST:event_BtnRegistrarApoderadoActionPerformed

    private void BtnModificarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarApoderadoActionPerformed
        // TODO add your handling code here:
        int seleccionado = this.tableApoderados.getSelectedRow();
        if (seleccionado > -1) {

            Object valor = ((DefaultTableModel) this.tableApoderados.getModel()).getValueAt(seleccionado, 0);
            int rutApoderado = Integer.parseInt(valor.toString());

            ModificarApoderadoView ModificarApod = new ModificarApoderadoView(rutApoderado);
            this.setVisible(false);
            ModificarApod.setLocationRelativeTo(null);
            ModificarApod.setVisible(true);
        }
    }//GEN-LAST:event_BtnModificarApoderadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuApoderadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroupPerfil;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnModificarApoderado;
    private javax.swing.JButton BtnRegistrarApoderado;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tableApoderados;
    // End of variables declaration//GEN-END:variables
}
