/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.Conexion;
import Dao.ApoderadoDAO;
import model.Apoderado;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose_
 */
public final class MenuApoderadoView extends javax.swing.JFrame {

    private ApoderadoDAO apoderadoDAO= new ApoderadoDAO();
    DefaultTableModel modelo;
    
    /**
     * Creates new form MenuPrincipalView
     */
    public MenuApoderadoView() {
        this.setMinimumSize(new Dimension(816,446));
        initComponents();
//        Conexion con = new Conexion();
//        con.conectar();
//        OcultarFormularioRegistrar();
//        this.jScrollPane1.setVisible(false);
//        this.CmbxCiudad.setModel(IDAO.obtener_Ciudad());
//        this.CmbxComuna.setModel(IDAO.obtener_Curso(curso));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupPerfil = new javax.swing.ButtonGroup();
        BtnModificarApoderado = new javax.swing.JButton();
        BtnRegistrarApoderado = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbListar = new javax.swing.JTable();
        LblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BtnModificarApoderado.setText("Modificar");
        BtnModificarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificarApoderado);
        BtnModificarApoderado.setBounds(230, 30, 120, 40);

        BtnRegistrarApoderado.setText("Registrar");
        BtnRegistrarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarApoderadoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrarApoderado);
        BtnRegistrarApoderado.setBounds(120, 30, 100, 40);

        BtnListar.setText("Listar");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnListar);
        BtnListar.setBounds(20, 30, 90, 40);

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver);
        BtnVolver.setBounds(410, 30, 79, 40);

        TbListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TbListar.setEnabled(false);
        jScrollPane1.setViewportView(TbListar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 700, 230);

        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(LblFondo);
        LblFondo.setBounds(-10, -10, 830, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarApoderado(){
        try {
        List<Apoderado> apoderado;
        modelo.setRowCount(0);
        apoderado = ApoderadoDAO.listarApoderado();
            for (Apoderado apoderadoa : apoderado) {
                Object[] obj= ApoderadoDAO.objetoApoderado(apoderadoa);
                modelo.addRow(obj);
                this.TbListar.setModel(modelo);
                
            }
        } catch (SQLException e) {
        }
    }
    
//    public void OcultarFormularioRegistrar(){
//        this.TxtRutApoderado.setVisible(false);
//        this.TxtNombreApoderado.setVisible(false);
//        this.TxtAPaternoApoderado.setVisible(false);
//        this.TxtAMaternoApoderado.setVisible(false);
//        this.TxtDireccionApoderado.setVisible(false);
//        this.TxtFNacimiento.setVisible(false);
//        this.TxtTelefonoApoderado.setVisible(false);
//        this.CmbxCiudad.setVisible(false);
//        this.CmbxComuna.setVisible(false);
//        this.TxtPassApoderado.setVisible(false);
//        this.TxtPassApoderado.setVisible(false);
//        this.TxtCorreoApoderado.setVisible(false);
//        this.RbtPerfilNo.setVisible(false);
//        this.RbtPerfilSi.setVisible(false);
//        
//    }
    
//        public void MostrarFormularioRegistrar(){
//        this.TxtRutApoderado.setVisible(true);
//        this.TxtNombreApoderado.setVisible(true);
//        this.TxtAPaternoApoderado.setVisible(true);
//        this.TxtAMaternoApoderado.setVisible(true);
//        this.TxtDireccionApoderado.setVisible(true);
//        this.TxtFNacimiento.setVisible(true);
//        this.TxtTelefonoApoderado.setVisible(true);
//        this.CmbxCiudad.setVisible(true);
//        this.CmbxComuna.setVisible(true);
//        this.TxtPassApoderado.setVisible(true);
//    }
    
    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        // TODO add your handling code here:
//        OcultarFormularioRegistrar();
        this.jScrollPane1.setVisible(true);
        modelo= new DefaultTableModel();

        modelo.addColumn("Rut");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Id Comuna");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellido paterno");
        modelo.addColumn("Apellido materno");
        modelo.addColumn("Fecha nacimiento");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Perfil");
        modelo.addColumn("Dirección");
        TbListar.setModel(modelo);
//        actualizarApoderado();
        Conexion con = new Conexion();
        ApoderadoDAO iapo = new ApoderadoDAO();
        actualizarApoderado();
        //actualizarRepresentante();
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipalView MenuPrin = new MenuPrincipalView();
        MenuPrin.setLocationRelativeTo(null);
        MenuPrin.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnRegistrarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarApoderadoActionPerformed
        // TODO add your handling code here:
        AgregarApoderadosView AgregarApod = new AgregarApoderadosView();
        this.setVisible(false);
        AgregarApod.setLocationRelativeTo(null);
        AgregarApod.setVisible(true);
//        this.jScrollPane1.setVisible(false);
//        MostrarFormularioRegistrar();
    }//GEN-LAST:event_BtnRegistrarApoderadoActionPerformed

    private void BtnModificarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarApoderadoActionPerformed
        // TODO add your handling code here:
        ModificarApoderadoView ModificarApod = new ModificarApoderadoView();
        this.setVisible(false);
        ModificarApod.setLocationRelativeTo(null);
        ModificarApod.setVisible(true);
    }//GEN-LAST:event_BtnModificarApoderadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApoderadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuApoderadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroupPerfil;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnModificarApoderado;
    private javax.swing.JButton BtnRegistrarApoderado;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JTable TbListar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
