/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.AseguradoraDAO;
import Dao.AutenticacionDAO;
import Dao.CiudadDAO;
import Dao.ColegioDAO;
import Dao.ComunaDAO;
import Dao.SeguroDAO;
import controller.SegurosController;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Seguro;

/**
 *
 * @author jose_
 */
public class MenuSegurosView extends javax.swing.JFrame {
    private SegurosController controller = new SegurosController();
    private SeguroDAO seguroDAO = new SeguroDAO();
    private AseguradoraDAO aseguradoraDAO = new AseguradoraDAO();

    DefaultTableModel modelo;

    private AutenticacionDAO autenticacionDAO = new AutenticacionDAO();
    private ColegioDAO colegioDAO = new ColegioDAO();
    private CiudadDAO ciudadDAO = new CiudadDAO();
    private ComunaDAO comunaDAO = new ComunaDAO();

    /**
     * Creates new form MenuColegioView
     */
    public MenuSegurosView() {
        this.setMinimumSize(new Dimension(100, 200));
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo1.png")).getImage());
        this.jpanelRegistrarSeguro.setVisible(false);
        this.btnModificarSeguros.setVisible(false);
        this.jPanelListarSeguros.setVisible(false);
        this.ComboAseguradora.setModel(aseguradoraDAO.obtenerAseguradoras());
        this.comboTipoSeguro.setModel(seguroDAO.obtenerSeguro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnListarColegio = new javax.swing.JPanel();
        BtnAgregarSeguro = new javax.swing.JButton();
        btnConsultarSeguros = new javax.swing.JButton();
        btnModificarSeguros = new javax.swing.JButton();
        VolverSeguro = new javax.swing.JButton();
        jPanelListarSeguros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSeguro = new javax.swing.JTable();
        jpanelRegistrarSeguro = new javax.swing.JPanel();
        lblTipoSeguro = new javax.swing.JLabel();
        comboTipoSeguro = new javax.swing.JComboBox<>();
        lblAseguradora = new javax.swing.JLabel();
        ComboAseguradora = new javax.swing.JComboBox<>();
        lblFechaIni = new javax.swing.JLabel();
        dateChooserFechaEvento = new com.toedter.calendar.JDateChooser();
        lblPrecioSeguro = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        BtnBorrarcampos = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        txtPrecioSeguro = new javax.swing.JTextField();
        lblFechaIni1 = new javax.swing.JLabel();
        dateChooserFechaFin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        btnListarColegio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Admistrador de Seguros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        BtnAgregarSeguro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnAgregarSeguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AddColegio2.png"))); // NOI18N
        BtnAgregarSeguro.setText("Agregar");
        BtnAgregarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarSeguroActionPerformed(evt);
            }
        });

        btnConsultarSeguros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsultarSeguros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        btnConsultarSeguros.setText("Consultar");
        btnConsultarSeguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSegurosActionPerformed(evt);
            }
        });

        btnModificarSeguros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificarSeguros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        btnModificarSeguros.setText("Eliminar");
        btnModificarSeguros.setEnabled(false);
        btnModificarSeguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSegurosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnListarColegioLayout = new javax.swing.GroupLayout(btnListarColegio);
        btnListarColegio.setLayout(btnListarColegioLayout);
        btnListarColegioLayout.setHorizontalGroup(
            btnListarColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListarColegioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAgregarSeguro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarSeguros)
                .addGap(18, 18, 18)
                .addComponent(btnModificarSeguros)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnListarColegioLayout.setVerticalGroup(
            btnListarColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListarColegioLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(btnListarColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificarSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        VolverSeguro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VolverSeguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return.png"))); // NOI18N
        VolverSeguro.setText("Volver");
        VolverSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverSeguroActionPerformed(evt);
            }
        });

        jPanelListarSeguros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listar Seguros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanelListarSeguros.setLayout(null);

        jTableSeguro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableSeguro);

        jPanelListarSeguros.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 470, 130);

        jpanelRegistrarSeguro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registrar Seguro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jpanelRegistrarSeguro.setLayout(null);

        lblTipoSeguro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoSeguro.setText("Seguro:");
        jpanelRegistrarSeguro.add(lblTipoSeguro);
        lblTipoSeguro.setBounds(70, 110, 140, 20);

        comboTipoSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpanelRegistrarSeguro.add(comboTipoSeguro);
        comboTipoSeguro.setBounds(150, 100, 200, 40);

        lblAseguradora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAseguradora.setText("Aseguradora:");
        jpanelRegistrarSeguro.add(lblAseguradora);
        lblAseguradora.setBounds(30, 50, 94, 20);

        ComboAseguradora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpanelRegistrarSeguro.add(ComboAseguradora);
        ComboAseguradora.setBounds(150, 40, 200, 40);

        lblFechaIni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaIni.setText("Fecha Inicio : ");
        jpanelRegistrarSeguro.add(lblFechaIni);
        lblFechaIni.setBounds(40, 210, 95, 20);
        jpanelRegistrarSeguro.add(dateChooserFechaEvento);
        dateChooserFechaEvento.setBounds(150, 200, 200, 30);

        lblPrecioSeguro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecioSeguro.setText("Precio:");
        jpanelRegistrarSeguro.add(lblPrecioSeguro);
        lblPrecioSeguro.setBounds(80, 160, 47, 20);

        lblMonto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpanelRegistrarSeguro.add(lblMonto);
        lblMonto.setBounds(180, 280, 190, 30);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpanelRegistrarSeguro.add(btnAgregar);
        btnAgregar.setBounds(120, 300, 260, 50);

        BtnBorrarcampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnBorrarcampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        BtnBorrarcampos.setText("Limpiar");
        BtnBorrarcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarcamposActionPerformed(evt);
            }
        });
        jpanelRegistrarSeguro.add(BtnBorrarcampos);
        BtnBorrarcampos.setBounds(120, 380, 120, 40);

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return.png"))); // NOI18N
        BtnCancelar.setText("Volver");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jpanelRegistrarSeguro.add(BtnCancelar);
        BtnCancelar.setBounds(250, 380, 130, 40);
        jpanelRegistrarSeguro.add(txtPrecioSeguro);
        txtPrecioSeguro.setBounds(150, 150, 200, 30);

        lblFechaIni1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaIni1.setText("Fecha Fin : ");
        jpanelRegistrarSeguro.add(lblFechaIni1);
        lblFechaIni1.setBounds(60, 260, 77, 20);
        jpanelRegistrarSeguro.add(dateChooserFechaFin);
        dateChooserFechaFin.setBounds(150, 250, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VolverSeguro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelRegistrarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelListarSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnListarColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(VolverSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpanelRegistrarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanelListarSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarSeguroActionPerformed
        // TODO add your handling code here:
        this.jpanelRegistrarSeguro.setVisible(true);
        this.jPanelListarSeguros.setVisible(false);
//        AgregarColegioView agregarColegio = new AgregarColegioView();
//        this.setVisible(false);
//        agregarColegio.setLocationRelativeTo(null);
//        agregarColegio.setVisible(true);
    }//GEN-LAST:event_BtnAgregarSeguroActionPerformed

    private void btnConsultarSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSegurosActionPerformed
        // TODO add your handling code here:
        this.jpanelRegistrarSeguro.setVisible(false);
        this.jPanelListarSeguros.setVisible(true);
        this.jScrollPane1.setVisible(true);

        DefaultTableModel modelotabla = this.controller.consultarSeguros();
        this.jTableSeguro.setModel(modelotabla);
        this.btnModificarSeguros.setVisible(true);
    }//GEN-LAST:event_btnConsultarSegurosActionPerformed

    private void btnModificarSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSegurosActionPerformed
        // TODO add your handling code here:
        int seleccionado = this.jTableSeguro.getSelectedRow();
        if (seleccionado > -1) {

            int confirm = JOptionPane.showConfirmDialog(null, "¿Está Seguro del seguro a eliminar?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {

                Object valor = ((DefaultTableModel) this.jTableSeguro.getModel()).getValueAt(seleccionado, 0);
                int idSeguro = Integer.parseInt(valor.toString());

                boolean eliminado = this.controller.eliminarSeguro(idSeguro);
                if (eliminado) {
                    ((DefaultTableModel) this.jTableSeguro.getModel()).removeRow(seleccionado);
                    JOptionPane.showMessageDialog(this, "Seguro Eliminado");
                }

            } else {
                System.out.println("Cancelación de eliminado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Colegio");
        }
    }//GEN-LAST:event_btnModificarSegurosActionPerformed

    private void VolverSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverSeguroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipalView MenuPrin = new MenuPrincipalView();
        MenuPrin.setLocationRelativeTo(null);
        MenuPrin.setVisible(true);
    }//GEN-LAST:event_VolverSeguroActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        try {

            String cmbseg = String.valueOf(ComboAseguradora.getSelectedItem());
            String cmbseg1 = aseguradoraDAO.obtenerIdAseguradora(cmbseg);
            int idaseguradora = Integer.parseInt(cmbseg1);
            System.out.println("id aseguradora : " + idaseguradora);

            String cmbseg2 = String.valueOf(comboTipoSeguro.getSelectedItem());
            String cmbseg3 = seguroDAO.obtenerIdSeguro(cmbseg2);
            int idseguro = Integer.parseInt(cmbseg3);
            System.out.println("id seguro : " + idseguro);

            int precio = Integer.parseInt(txtPrecioSeguro.getText());
            System.out.println("Precio: " + precio);

          
            String fecha_ini = formato.format(dateChooserFechaEvento.getDate());
            System.out.println("Fecha Inicio : " + fecha_ini);

            
            String fecha_fin = formato.format(dateChooserFechaFin.getDate());
            System.out.println("Fecha Fin : " + fecha_fin);

            Seguro seguro = new Seguro();
            seguro.setIdTipoSeguro(idseguro);
            seguro.setIdAseguradora(idaseguradora);
            seguro.setPrecio(precio);
            seguro.setFechaIni(fecha_ini);
            seguro.setFechFin(fecha_fin);

            controller.agregarSeguro(seguro);
            JOptionPane.showMessageDialog(this, "Seguro registrado");

        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void BtnBorrarcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarcamposActionPerformed

        ComboAseguradora.setSelectedIndex(0);
        comboTipoSeguro.setSelectedIndex(0);
        txtPrecioSeguro.setText(" ");
        dateChooserFechaEvento.setDate(null);
        dateChooserFechaFin.setDate(null);
    }//GEN-LAST:event_BtnBorrarcamposActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipalView MenuPrin = new MenuPrincipalView();
        MenuPrin.setLocationRelativeTo(null);
        MenuPrin.setVisible(true);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSegurosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSegurosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSegurosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSegurosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSegurosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarSeguro;
    private javax.swing.JButton BtnBorrarcampos;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JComboBox<String> ComboAseguradora;
    private javax.swing.JButton VolverSeguro;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultarSeguros;
    private javax.swing.JPanel btnListarColegio;
    private javax.swing.JButton btnModificarSeguros;
    private javax.swing.JComboBox<String> comboTipoSeguro;
    private com.toedter.calendar.JDateChooser dateChooserFechaEvento;
    private com.toedter.calendar.JDateChooser dateChooserFechaFin;
    private javax.swing.JPanel jPanelListarSeguros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSeguro;
    private javax.swing.JPanel jpanelRegistrarSeguro;
    private javax.swing.JLabel lblAseguradora;
    private javax.swing.JLabel lblFechaIni;
    private javax.swing.JLabel lblFechaIni1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblPrecioSeguro;
    private javax.swing.JLabel lblTipoSeguro;
    private javax.swing.JTextField txtPrecioSeguro;
    // End of variables declaration//GEN-END:variables
}
