/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.PdfDAO;

import controller.PDFController;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Tabla_PdfVO;

/**
 *
 * @author David
 */
public class MenuPdfView extends javax.swing.JFrame {

    private PdfDAO pdfdao = new PdfDAO();
    private PDFController controller = new PDFController();

    /**
     * Creates new form MenuPdfView
     */
    Tabla_PdfVO tpdf = new Tabla_PdfVO();
    String ruta_default = "C:/portafolio/PDF/";
    String ruta_archivo = "";
    String nombre_archivo = " ";

    public MenuPdfView() {
        this.setMinimumSize(new Dimension(880, 500));
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo1.png")).getImage());
        this.CmbContrato.setModel(pdfdao.obtenerContrato());

        this.tablePdf.setVisible(true);
        DefaultTableModel modelotabla = this.controller.consultarContratos();
        this.tablePdf.setModel(modelotabla);

        //termino tabla
        activa_boton(false, true, true);
        CmbContrato.setEnabled(false);
        this.btnseleccionarPdf.setEnabled(false);
    }

    public void activa_boton(boolean a, boolean b, boolean c) {
        btnGuardarPdf.setEnabled(a);
        btnEliminarPdf.setEnabled(c);
        CmbContrato.setSelectedIndex(0);
        btnseleccionarPdf.setText("Seleccionar PDF");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSeleccionContrato = new javax.swing.JLabel();
        lblSeleccionarPdf = new javax.swing.JLabel();
        CmbContrato = new javax.swing.JComboBox<>();
        btnseleccionarPdf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePdf = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNuevoPdf = new javax.swing.JButton();
        btnGuardarPdf = new javax.swing.JButton();
        btnEliminarPdf = new javax.swing.JButton();
        btnCancelarPdf = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guardar y Leer PDF");
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Subir Archivo PDF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(null);

        lblSeleccionContrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSeleccionContrato.setText("Seleccione Contrato:");
        jPanel2.add(lblSeleccionContrato);
        lblSeleccionContrato.setBounds(56, 47, 143, 17);

        lblSeleccionarPdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSeleccionarPdf.setText("Seleccionar archivo:");
        jPanel2.add(lblSeleccionarPdf);
        lblSeleccionarPdf.setBounds(61, 99, 143, 17);

        CmbContrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CmbContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Contrato" }));
        jPanel2.add(CmbContrato);
        CmbContrato.setBounds(216, 37, 243, 44);

        btnseleccionarPdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnseleccionarPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PDF.png"))); // NOI18N
        btnseleccionarPdf.setText("Seleccionar PDF");
        btnseleccionarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarPdfActionPerformed(evt);
            }
        });
        jPanel2.add(btnseleccionarPdf);
        btnseleccionarPdf.setBounds(216, 88, 243, 57);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 40, 560, 160);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GUARDAR ARCHIVO ESCANEADO POR CONTRATO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 790, 21);

        tablePdf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablePdf);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 210, 560, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel3.setLayout(null);

        btnNuevoPdf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevoPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NewPDF.png"))); // NOI18N
        btnNuevoPdf.setText("Nuevo");
        btnNuevoPdf.setMaximumSize(new java.awt.Dimension(71, 23));
        btnNuevoPdf.setMinimumSize(new java.awt.Dimension(71, 23));
        btnNuevoPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPdfActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevoPdf);
        btnNuevoPdf.setBounds(10, 10, 170, 45);

        btnGuardarPdf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardarPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SavePDF.png"))); // NOI18N
        btnGuardarPdf.setText("Guardar");
        btnGuardarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPdfActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarPdf);
        btnGuardarPdf.setBounds(10, 60, 170, 45);

        btnEliminarPdf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DeletePDF.png"))); // NOI18N
        btnEliminarPdf.setText("Eliminar");
        btnEliminarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPdfActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarPdf);
        btnEliminarPdf.setBounds(10, 110, 170, 45);

        btnCancelarPdf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelarPdf.setText("Cancelar");
        btnCancelarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPdfActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelarPdf);
        btnCancelarPdf.setBounds(10, 160, 170, 45);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 210, 200, 230);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(10, 20, 200, 180);

        BtnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return.png"))); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver);
        BtnVolver.setBounds(630, 370, 150, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnseleccionarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarPdfActionPerformed

        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.btnseleccionarPdf.setText("" + j.getSelectedFile().getName());
            nombre_archivo = j.getSelectedFile().getName();
            ruta_archivo = ruta_default + nombre_archivo;
            File archivopdforigen = new File(j.getSelectedFile().getAbsolutePath());
            File destinopdf = new File(ruta_archivo);

            try {
                InputStream in = new FileInputStream(archivopdforigen);
                OutputStream out = new FileOutputStream(destinopdf);

                byte[] buf = new byte[1024];
                int len;

                while ((len = in.read(buf)) > 0) {
                    out.write(buf, 0, len);
                }

                in.close();
                out.close();
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        } else {
        }
    }//GEN-LAST:event_btnseleccionarPdfActionPerformed

    private void btnGuardarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPdfActionPerformed

        //Obtención rut agente
        int idcontra = Integer.parseInt(String.valueOf(CmbContrato.getSelectedItem()));
        int idcontrato = pdfdao.obtenerIdContrato(idcontra);

        boolean existeArchivo = this.pdfdao.existeArchivoPorIdContrato(idcontrato);

        if (existeArchivo) {
            JOptionPane.showMessageDialog(this, "Ya existe un archivo para este contrato.");
            return;

        }

        //PRUEBA
        //TERMINO PRUEBA
        System.out.println("nombre:" + nombre_archivo);
        System.out.println("ruta:" + ruta_archivo);
        System.out.println("idcontrato " + idcontrato);

        try {

            pdfdao.agregarPdf(nombre_archivo, ruta_archivo, idcontrato);
            // guardar_pdf(idcontrato,nombre_archivo,ruta_archivo);
            //tpdf.visualizar_PdfVO(tabla);

            //TABLA
            this.tablePdf.setVisible(true);
            DefaultTableModel modelotabla = this.controller.consultarContratos();
            this.tablePdf.setModel(modelotabla);

            activa_boton(false, true, true);
            CmbContrato.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarPdfActionPerformed

    private void btnEliminarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPdfActionPerformed

        int seleccionado = this.tablePdf.getSelectedRow();
        if (seleccionado > -1) {

            int confirm = JOptionPane.showConfirmDialog(null, "¿Está Seguro del Archivo a eliminar?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {

                Object valor = ((DefaultTableModel) this.tablePdf.getModel()).getValueAt(seleccionado, 0);
                int idContrato = Integer.parseInt(valor.toString());

                //ELIMINAR ARCHIVO REAL
                String rutadlt = pdfdao.obtenerRutaPdf(idContrato);
                File destino = new File(rutadlt);
                destino.delete();

                boolean eliminado = this.controller.eliminararchivopdf(idContrato);
                if (eliminado) {
                    ((DefaultTableModel) this.tablePdf.getModel()).removeRow(seleccionado);
                    JOptionPane.showMessageDialog(this, "Archivo Eliminado");
                }

            } else {
                System.out.println("Cancelación de eliminado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un contrato");
        }
    }//GEN-LAST:event_btnEliminarPdfActionPerformed

    private void btnCancelarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPdfActionPerformed
//        activa_boton(false, false, false);

        CmbContrato.setEnabled(false);
        btnseleccionarPdf.setEnabled(false);
        btnGuardarPdf.setEnabled(false);
        btnEliminarPdf.setEnabled(true);

        File destino = new File(ruta_archivo);
        destino.delete();
    }//GEN-LAST:event_btnCancelarPdfActionPerformed

    private void btnNuevoPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPdfActionPerformed
        activa_boton(true, false, false);
        CmbContrato.setEnabled(true);
        btnseleccionarPdf.setEnabled(true);
        ruta_archivo = "";


    }//GEN-LAST:event_btnNuevoPdfActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuContratosView menuContratos = new MenuContratosView();
        menuContratos.setLocationRelativeTo(null);
        menuContratos.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPdfView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPdfView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPdfView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPdfView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPdfView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox<String> CmbContrato;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnCancelarPdf;
    private javax.swing.JButton btnEliminarPdf;
    private javax.swing.JButton btnGuardarPdf;
    private javax.swing.JButton btnNuevoPdf;
    private javax.swing.JButton btnseleccionarPdf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSeleccionContrato;
    private javax.swing.JLabel lblSeleccionarPdf;
    private javax.swing.JTable tablePdf;
    // End of variables declaration//GEN-END:variables
}
