/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import AppPackage.AnimationClass;
import Dao.AutenticacionDAO;
import Dao.CiudadDAO;
import Dao.ColegioDAO;
import Dao.ComunaDAO;
import controller.ColegioController;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KeyValue;
import utils.GuiUtils;

/**
 *
 * @author jose_
 */
public class MenuColegioView extends javax.swing.JFrame {

    private ColegioController controller = new ColegioController();

    DefaultTableModel modelo;

    private AutenticacionDAO autenticacionDAO = new AutenticacionDAO();
    private ColegioDAO colegioDAO = new ColegioDAO();
    private CiudadDAO ciudadDAO = new CiudadDAO();
    private ComunaDAO comunaDAO = new ComunaDAO();

    /**
     * Creates new form MenuColegioView
     */
    public MenuColegioView() {
        this.setUndecorated(true);
        this.setMinimumSize(new Dimension(955,623));
        initComponents();
        setIconImage(GuiUtils.getImage("logo1.png"));
        this.cmbCiudad.setModel(ciudadDAO.obtenerCiudades());
        this.jPanelAgregarColegio.setVisible(false);
        this.btnModificarColegio.setVisible(false);
        this.jPanelListarColegios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblLogoMenu = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnListarColegio = new javax.swing.JPanel();
        btnAgregarColegio = new javax.swing.JButton();
        btnConsultarColegios = new javax.swing.JButton();
        btnModificarColegio = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanelAgregarColegio = new javax.swing.JPanel();
        LblNombreColegio = new javax.swing.JLabel();
        TxtNombreColegio = new javax.swing.JTextField();
        LblDireccionColegio = new javax.swing.JLabel();
        TxtDireccionColegio = new javax.swing.JTextField();
        LblCiudadColegio = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox<>();
        cmbComuna = new javax.swing.JComboBox<>();
        LblComunaColegio = new javax.swing.JLabel();
        LblTelefonoColegio = new javax.swing.JLabel();
        TxtTelefonoColegio = new javax.swing.JTextField();
        btnAgregarColegio1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelListarColegios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableColegio = new javax.swing.JTable();
        btnAgregarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel4.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, 30));

        lblLogoMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogoMenu.setText("On Tour");
        jPanel4.add(lblLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Exit.png"))); // NOI18N
        BtnCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseMoved(evt);
            }
        });
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseExited(evt);
            }
        });
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        jPanel4.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 950, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 177, 159));

        btnListarColegio.setBackground(new java.awt.Color(255, 255, 255));
        btnListarColegio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 161, 215), 5, true), "Admistrador de Colegio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        btnListarColegio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarColegio.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarColegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AddColegio2.png"))); // NOI18N
        btnAgregarColegio.setText("Agregar");
        btnAgregarColegio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAgregarColegioMouseMoved(evt);
            }
        });
        btnAgregarColegio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarColegioMouseExited(evt);
            }
        });
        btnAgregarColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColegioActionPerformed(evt);
            }
        });
        btnListarColegio.add(btnAgregarColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 59, -1, 65));

        btnConsultarColegios.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarColegios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsultarColegios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        btnConsultarColegios.setText("Consultar");
        btnConsultarColegios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnConsultarColegiosMouseMoved(evt);
            }
        });
        btnConsultarColegios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarColegiosMouseExited(evt);
            }
        });
        btnConsultarColegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarColegiosActionPerformed(evt);
            }
        });
        btnListarColegio.add(btnConsultarColegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 59, -1, 65));

        btnModificarColegio.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificarColegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        btnModificarColegio.setText("Eliminar");
        btnModificarColegio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnModificarColegioMouseMoved(evt);
            }
        });
        btnModificarColegio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarColegioMouseExited(evt);
            }
        });
        btnModificarColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarColegioActionPerformed(evt);
            }
        });
        btnListarColegio.add(btnModificarColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 59, -1, 65));

        jPanel1.add(btnListarColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 570, 150));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(12, 161, 215));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return1.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolver.setIconTextGap(-10);
        btnVolver.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnVolver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVolverMouseMoved(evt);
            }
        });
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 140, 60));

        jPanelAgregarColegio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAgregarColegio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 161, 215), 5, true), "Registrar Colegio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanelAgregarColegio.setLayout(null);

        LblNombreColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblNombreColegio.setText("Nombre: ");
        jPanelAgregarColegio.add(LblNombreColegio);
        LblNombreColegio.setBounds(40, 60, 100, 22);

        TxtNombreColegio.setBorder(null);
        jPanelAgregarColegio.add(TxtNombreColegio);
        TxtNombreColegio.setBounds(120, 50, 220, 40);

        LblDireccionColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblDireccionColegio.setText("Dirección: ");
        jPanelAgregarColegio.add(LblDireccionColegio);
        LblDireccionColegio.setBounds(30, 220, 100, 22);

        TxtDireccionColegio.setBorder(null);
        jPanelAgregarColegio.add(TxtDireccionColegio);
        TxtDireccionColegio.setBounds(120, 200, 220, 40);

        LblCiudadColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblCiudadColegio.setText("Ciudad: ");
        jPanelAgregarColegio.add(LblCiudadColegio);
        LblCiudadColegio.setBounds(50, 110, 90, 22);

        cmbCiudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ciudad" }));
        cmbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCiudadItemStateChanged(evt);
            }
        });
        jPanelAgregarColegio.add(cmbCiudad);
        cmbCiudad.setBounds(130, 100, 210, 40);

        cmbComuna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Comuna" }));
        jPanelAgregarColegio.add(cmbComuna);
        cmbComuna.setBounds(130, 150, 210, 40);

        LblComunaColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblComunaColegio.setText("Comuna: ");
        jPanelAgregarColegio.add(LblComunaColegio);
        LblComunaColegio.setBounds(40, 160, 100, 22);

        LblTelefonoColegio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTelefonoColegio.setText("Teléfono:");
        jPanelAgregarColegio.add(LblTelefonoColegio);
        LblTelefonoColegio.setBounds(30, 260, 100, 22);

        TxtTelefonoColegio.setBorder(null);
        jPanelAgregarColegio.add(TxtTelefonoColegio);
        TxtTelefonoColegio.setBounds(120, 250, 220, 40);

        btnAgregarColegio1.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarColegio1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarColegio1.setForeground(new java.awt.Color(12, 161, 215));
        btnAgregarColegio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnAgregarColegio1.setText("Agregar");
        btnAgregarColegio1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAgregarColegio1MouseMoved(evt);
            }
        });
        btnAgregarColegio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarColegio1MouseExited(evt);
            }
        });
        btnAgregarColegio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColegio1ActionPerformed(evt);
            }
        });
        jPanelAgregarColegio.add(btnAgregarColegio1);
        btnAgregarColegio1.setBounds(120, 300, 220, 50);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelAgregarColegio.add(jSeparator1);
        jSeparator1.setBounds(40, 290, 300, 10);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanelAgregarColegio.add(jSeparator2);
        jSeparator2.setBounds(40, 90, 300, 10);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanelAgregarColegio.add(jSeparator3);
        jSeparator3.setBounds(40, 240, 300, 10);

        jPanel1.add(jPanelAgregarColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 425, 370));

        jPanelListarColegios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListarColegios.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 161, 215), 5, true), "Listar Colegios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanelListarColegios.setLayout(null);

        jTableColegio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableColegio);

        jPanelListarColegios.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 450, 135);

        jPanel1.add(jPanelListarColegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 488, 180));

        btnAgregarArchivo.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarArchivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        btnAgregarArchivo.setText("Cursos");
        btnAgregarArchivo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAgregarArchivoMouseMoved(evt);
            }
        });
        btnAgregarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarArchivoMouseExited(evt);
            }
        });
        btnAgregarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 150, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 950, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColegioActionPerformed
        // TODO add your handling code here:
        this.jPanelAgregarColegio.setVisible(true);
        this.jPanelListarColegios.setVisible(false);
//        AgregarColegioView agregarColegio = new AgregarColegioView();
//        this.setVisible(false);
//        agregarColegio.setLocationRelativeTo(null);
//        agregarColegio.setVisible(true);
    }//GEN-LAST:event_btnAgregarColegioActionPerformed

    private void cmbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCiudadItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String comuna = String.valueOf(cmbCiudad.getSelectedItem());
            this.cmbComuna.setModel(comunaDAO.obtenerComunas(comuna));
        }
    }//GEN-LAST:event_cmbCiudadItemStateChanged

    private void btnAgregarColegio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColegio1ActionPerformed
        // TODO add your handling code here:
        try {

            KeyValue comuna = (KeyValue) cmbComuna.getSelectedItem();
            int idcomuna = comuna.getId();

            String nombre = TxtNombreColegio.getText();
            String direccion = TxtDireccionColegio.getText();
            int telefono = Integer.parseInt(TxtTelefonoColegio.getText());

            colegioDAO.agregarColegio(idcomuna, nombre, direccion, telefono);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAgregarColegio1ActionPerformed

    private void btnConsultarColegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarColegiosActionPerformed

        this.jPanelAgregarColegio.setVisible(false);
        this.jPanelListarColegios.setVisible(true);
        this.jScrollPane1.setVisible(true);

        DefaultTableModel modelotabla = this.controller.consultarColegios();
        this.jTableColegio.setModel(modelotabla);
        this.btnModificarColegio.setVisible(true);
    }//GEN-LAST:event_btnConsultarColegiosActionPerformed

    private void btnModificarColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarColegioActionPerformed
        // TODO add your handling code here:
        int seleccionado = this.jTableColegio.getSelectedRow();
        if (seleccionado > -1) {

            int confirm = JOptionPane.showConfirmDialog(null, "¿Está Seguro del colegio a eliminar?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {

                Object valor = ((DefaultTableModel) this.jTableColegio.getModel()).getValueAt(seleccionado, 0);
                int idColegio = Integer.parseInt(valor.toString());

                boolean eliminado = this.controller.eliminarColegio(idColegio);
                if (eliminado) {
                    ((DefaultTableModel) this.jTableColegio.getModel()).removeRow(seleccionado);
                    JOptionPane.showMessageDialog(this, "Colegio Eliminado");
                }

            } else {
                System.out.println("Cancelación de eliminado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Colegio");
        }
    }//GEN-LAST:event_btnModificarColegioActionPerformed

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(MenuPrincipalView.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void BtnCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseMoved
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_BtnCerrarMouseMoved

    private void BtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseExited
        // TODO add your handling code here:
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_BtnCerrarMouseExited

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir de la aplicación?");
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void btnVolverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseMoved
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnVolverMouseMoved

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        // TODO add your handling code here:
        btnVolver.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipalView MenuPrin = new MenuPrincipalView();
        MenuPrin.setLocationRelativeTo(null);
        MenuPrin.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarColegioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarColegioMouseMoved
        // TODO add your handling code here:
        btnAgregarColegio.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnAgregarColegioMouseMoved

    private void btnAgregarColegioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarColegioMouseExited
        // TODO add your handling code here:
        btnAgregarColegio.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnAgregarColegioMouseExited

    private void btnConsultarColegiosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarColegiosMouseMoved
        // TODO add your handling code here:
        btnConsultarColegios.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnConsultarColegiosMouseMoved

    private void btnConsultarColegiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarColegiosMouseExited
        // TODO add your handling code here:
        btnConsultarColegios.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnConsultarColegiosMouseExited

    private void btnModificarColegioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarColegioMouseMoved
        // TODO add your handling code here:
        btnModificarColegio.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnModificarColegioMouseMoved

    private void btnModificarColegioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarColegioMouseExited
        // TODO add your handling code here:
        btnModificarColegio.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnModificarColegioMouseExited

    private void btnAgregarColegio1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarColegio1MouseMoved
        // TODO add your handling code here:
        btnAgregarColegio1.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnAgregarColegio1MouseMoved

    private void btnAgregarColegio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarColegio1MouseExited
        // TODO add your handling code here:
        btnAgregarColegio1.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnAgregarColegio1MouseExited

    private void btnAgregarArchivoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarArchivoMouseMoved
        // TODO add your handling code here:
        btnAgregarArchivo.setBackground((new java.awt.Color(231, 165, 165)));
    }//GEN-LAST:event_btnAgregarArchivoMouseMoved

    private void btnAgregarArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarArchivoMouseExited
        // TODO add your handling code here:
        btnAgregarArchivo.setBackground((new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_btnAgregarArchivoMouseExited

    private void btnAgregarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArchivoActionPerformed
        // TODO add your handling code here:
        AgregarCursosView agregarCursos = new AgregarCursosView();
        this.setVisible(false);
        agregarCursos.setLocationRelativeTo(null);
        agregarCursos.setVisible(true);
    }//GEN-LAST:event_btnAgregarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuColegioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuColegioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuColegioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuColegioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuColegioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JLabel LblCiudadColegio;
    private javax.swing.JLabel LblComunaColegio;
    private javax.swing.JLabel LblDireccionColegio;
    private javax.swing.JLabel LblNombreColegio;
    private javax.swing.JLabel LblTelefonoColegio;
    private javax.swing.JTextField TxtDireccionColegio;
    private javax.swing.JTextField TxtNombreColegio;
    private javax.swing.JTextField TxtTelefonoColegio;
    private javax.swing.JButton btnAgregarArchivo;
    private javax.swing.JButton btnAgregarColegio;
    private javax.swing.JButton btnAgregarColegio1;
    private javax.swing.JButton btnConsultarColegios;
    private javax.swing.JPanel btnListarColegio;
    private javax.swing.JButton btnModificarColegio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbComuna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAgregarColegio;
    private javax.swing.JPanel jPanelListarColegios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableColegio;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoMenu;
    private javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables
}
