/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.CiudadDAO;
import Dao.ColegioDAO;
import Dao.ComunaDAO;
import Dao.ContratoDAO;
import controller.AlumnosController;
import controller.ApoderadosController;
import controller.ContratosController;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Alumno;
import model.Ciudad;
import model.Colegio;
import model.Comuna;
import model.KeyValue;
import utils.GuiUtils;

/**
 *
 * @author corellana
 */
public class ModificarAlumnosView extends javax.swing.JFrame {

    private AlumnosController controller = new AlumnosController();
    private CiudadDAO ciudadDAO = new CiudadDAO();
    private ComunaDAO comunaDAO = new ComunaDAO();
    private ContratoDAO contratoDao = new ContratoDAO();
    private ColegioDAO colegioDao = new ColegioDAO();
    

    /**
     * Creates new form ModificarApoderadoView
     */

    /**
     *
     * @param rutApoderado rutApoderado
     */
    public ModificarAlumnosView(int rutAlumno) {

        this.setMinimumSize(new Dimension(478, 600));
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo1.png")).getImage());
        this.cmbCiudad.setModel(ciudadDAO.obtenerCiudades());
     this.cmbColegio.setModel(GuiUtils.createModelFromList(contratoDao.obtenerColegios()));
        if (rutAlumno > 0) {
            this.txtRut.setText(String.valueOf(rutAlumno));
            this.btnBuscarxRut.doClick();
        }
        
        txtrutapoderado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnmodificar = new javax.swing.JButton();
        btnBuscarxRut = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAppPaterno = new javax.swing.JTextField();
        txtAppMaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbCiudad = new javax.swing.JComboBox<>();
        cmbComuna = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFNacimiento = new javax.swing.JTextField();
        lblmensaje = new javax.swing.JLabel();
        cmbColegio = new javax.swing.JComboBox<>();
        cmbCurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        txtrutapoderado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnmodificar.setText("Modificar Alumno");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar);
        btnmodificar.setBounds(140, 460, 220, 40);

        btnBuscarxRut.setBackground(new java.awt.Color(204, 0, 204));
        btnBuscarxRut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarxRut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ShearchApoderado.png"))); // NOI18N
        btnBuscarxRut.setText("Buscar");
        btnBuscarxRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarxRutActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarxRut);
        btnBuscarxRut.setBounds(290, 10, 170, 60);

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(382, 488, 83, 29);

        jLabel1.setText("Rut Alumno:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 17, 78, 16);
        getContentPane().add(txtRut);
        txtRut.setBounds(118, 14, 122, 26);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(86, 80, 54, 16);
        getContentPane().add(txtNombreUsuario);
        txtNombreUsuario.setBounds(154, 77, 228, 26);

        jLabel4.setText("Apellido Paterno:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(35, 109, 107, 16);

        jLabel5.setText("Apellido Materno:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(35, 138, 111, 16);

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(76, 199, 59, 14);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(12, 45, 399, 6);

        jLabel7.setText("Ciudad:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(87, 228, 48, 16);

        lblComuna.setText("Comuna:");
        getContentPane().add(lblComuna);
        lblComuna.setBounds(79, 260, 56, 16);

        jLabel9.setText("Dirección:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 360, 64, 16);
        getContentPane().add(txtAppPaterno);
        txtAppPaterno.setBounds(154, 106, 228, 26);
        getContentPane().add(txtAppMaterno);
        txtAppMaterno.setBounds(154, 135, 228, 26);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(154, 199, 228, 26);

        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ciudad" }));
        cmbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCiudadItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbCiudad);
        cmbCiudad.setBounds(154, 228, 228, 27);

        cmbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Comuna" }));
        getContentPane().add(cmbComuna);
        cmbComuna.setBounds(154, 257, 228, 27);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(150, 350, 228, 26);

        jLabel12.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(12, 167, 135, 16);
        getContentPane().add(txtFNacimiento);
        txtFNacimiento.setBounds(154, 164, 228, 26);

        lblmensaje.setForeground(new java.awt.Color(255, 51, 0));
        lblmensaje.setText("jLabel13");
        getContentPane().add(lblmensaje);
        lblmensaje.setBounds(40, 440, 301, 16);

        cmbColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColegio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbColegioItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbColegio);
        cmbColegio.setBounds(150, 290, 230, 27);

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCurso);
        cmbCurso.setBounds(150, 320, 230, 27);

        jLabel3.setText("Colegio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 290, 50, 16);

        lblCurso.setText("Curso");
        getContentPane().add(lblCurso);
        lblCurso.setBounds(90, 330, 53, 16);

        txtrutapoderado.setText("jTextField1");
        getContentPane().add(txtrutapoderado);
        txtrutapoderado.setBounds(150, 390, 80, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarxRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarxRutActionPerformed
        lblmensaje.setText("");
        try {
            //Obtener apoderado
            String rut = txtRut.getText();

            Alumno alu = this.controller.buscaralumnoxrut(Integer.parseInt(rut));

            txtNombreUsuario.setText(String.valueOf(alu.getNombre()));
            txtAppPaterno.setText(String.valueOf(alu.getaPaterno()));
            txtAppMaterno.setText(String.valueOf(alu.getaMaterno()));
            txtFNacimiento.setText(String.valueOf(alu.getFechaNacimiento()));
            txtTelefono.setText(String.valueOf(alu.getTelefono()));
            txtDireccion.setText(String.valueOf(alu.getDireccion()));
            txtrutapoderado.setText(String.valueOf(alu.getRut_apoderado()));

            int idComuna = alu.getIdcomuna();
            Comuna comuna = comunaDAO.obtenerComunaPorId(idComuna);
            Ciudad ciudad = ciudadDAO.obtenerCiudadPorId(comuna.getIdCiudad());
            
            
            
            Colegio colegio = colegioDao.buscarColegioPorId(idComuna);

            cmbCiudad.setSelectedItem(new KeyValue(ciudad.getId(), ciudad.getNombre()));

            this.cmbComuna.setModel(comunaDAO.obtenerComunas(ciudad.getNombre()));
            
          

            cmbComuna.setSelectedItem(new KeyValue(comuna.getId(), comuna.getNombre()));

        } catch (Exception e) {
            lblmensaje.setText("El Objeto de Busqueda, no existe.");
        }
    }//GEN-LAST:event_btnBuscarxRutActionPerformed

    private void cmbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCiudadItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String ciudad = String.valueOf(cmbCiudad.getSelectedItem());
            this.cmbComuna.setModel(comunaDAO.obtenerComunas(ciudad));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCiudadItemStateChanged

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        try {
            int rut = Integer.parseInt(txtRut.getText());
            String nombre = txtNombreUsuario.getText();
            String aPaterno = txtAppPaterno.getText();
            String aMaterno = txtAppMaterno.getText();
            int telefono = Integer.parseInt(txtTelefono.getText());
            String fnacimiento = txtFNacimiento.getText();
            int rutapoderado = Integer.parseInt(txtrutapoderado.getText());
            if (txtTelefono.getText().length() != 9) {
                throw new Exception("Número de teléfono invalido");
            }

             KeyValue comuna = (KeyValue) cmbComuna.getSelectedItem();

            if ("Seleccione Comuna".equals(comuna.getText())) {
                throw new Exception("Seleccione Ciudad y Comuna");
            }

            String combocur = String.valueOf(cmbCurso.getSelectedItem());
            String combocur1 = contratoDao.obtenerIdCurso(combocur);
            int idcurso = Integer.parseInt(combocur1);

            int idcomuna = comuna.getId();

            String direccion = txtDireccion.getText();
            
            Alumno alumno = new Alumno();
            alumno.setRut(rut);
            alumno.setRut_apoderado(rutapoderado);
            alumno.setIdcomuna(idcomuna);
            alumno.setIdcurso(idcurso);
            alumno.setFechaNacimiento(fnacimiento);
            alumno.setNombre(nombre);
            alumno.setaPaterno(aPaterno);
            alumno.setaMaterno(aMaterno);
            alumno.setTelefono(telefono);
            alumno.setDireccion(direccion);

           controller.actualizarAlumno(alumno);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuApoderadoView MenuApode = new MenuApoderadoView();
        MenuApode.setLocationRelativeTo(null);
        MenuApode.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoActionPerformed

    private void cmbColegioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbColegioItemStateChanged
        // TODO add your handling code here:
        
        
       if (evt.getStateChange() == ItemEvent.SELECTED) {
            String curso;
            curso = String.valueOf(cmbColegio.getSelectedItem());
            this.cmbCurso.setModel(GuiUtils.createModelFromList(contratoDao.obtenerCursos(curso)));
        }
    }//GEN-LAST:event_cmbColegioItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAlumnosView(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarxRut;
    private javax.swing.JButton btnmodificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbColegio;
    private javax.swing.JComboBox<String> cmbComuna;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtAppMaterno;
    private javax.swing.JTextField txtAppPaterno;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFNacimiento;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtrutapoderado;
    // End of variables declaration//GEN-END:variables
}
